// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Laptev_Pham_Project.Migrations
{
    [DbContext(typeof(FlightsDBContext))]
    [Migration("20181109163042_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Laptev_Pham_Project.Models.ArrivalCity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName");

                    b.HasKey("ID");

                    b.ToTable("ArrivalCity");
                });

            modelBuilder.Entity("Laptev_Pham_Project.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Laptev_Pham_Project.Models.DepartureCity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName");

                    b.HasKey("ID");

                    b.ToTable("DepartureCity");
                });

            modelBuilder.Entity("Laptev_Pham_Project.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArrivalCityID");

                    b.Property<int?>("DepartureCityID");

                    b.Property<string>("FlightName");

                    b.HasKey("ID");

                    b.HasIndex("ArrivalCityID");

                    b.HasIndex("DepartureCityID");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("Laptev_Pham_Project.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArrivalCityNameID");

                    b.Property<int?>("DepartureCityNameID");

                    b.Property<int?>("FlightID");

                    b.Property<int?>("TicketID");

                    b.HasKey("ID");

                    b.HasIndex("ArrivalCityNameID");

                    b.HasIndex("DepartureCityNameID");

                    b.HasIndex("FlightID");

                    b.HasIndex("TicketID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Laptev_Pham_Project.Models.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlightID");

                    b.Property<int>("Price");

                    b.Property<int>("TicketType");

                    b.HasKey("ID");

                    b.HasIndex("FlightID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Laptev_Pham_Project.Models.Flight", b =>
                {
                    b.HasOne("Laptev_Pham_Project.Models.ArrivalCity", "ArrivalCity")
                        .WithMany()
                        .HasForeignKey("ArrivalCityID");

                    b.HasOne("Laptev_Pham_Project.Models.DepartureCity", "DepartureCity")
                        .WithMany()
                        .HasForeignKey("DepartureCityID");
                });

            modelBuilder.Entity("Laptev_Pham_Project.Models.Order", b =>
                {
                    b.HasOne("Laptev_Pham_Project.Models.ArrivalCity", "ArrivalCityName")
                        .WithMany()
                        .HasForeignKey("ArrivalCityNameID");

                    b.HasOne("Laptev_Pham_Project.Models.DepartureCity", "DepartureCityName")
                        .WithMany()
                        .HasForeignKey("DepartureCityNameID");

                    b.HasOne("Laptev_Pham_Project.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightID");

                    b.HasOne("Laptev_Pham_Project.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketID");
                });

            modelBuilder.Entity("Laptev_Pham_Project.Models.Ticket", b =>
                {
                    b.HasOne("Laptev_Pham_Project.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightID");
                });
#pragma warning restore 612, 618
        }
    }
}
